# Generated by Django 3.2.4 on 2021-06-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210630_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stats',
            field=models.BinaryField(default=False),
        ),
    ]
