# Generated by Django 3.2.4 on 2021-06-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stats',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
